### ISSUE TITLE
Learn MongoDB

### ISSUE THREAD

**Issue by c78867886** [c78867886/TwitterBaby#1]
### Plz visit the URL to know how to use Mongoose.
> https://juejin.im/entry/596324ec51882568cf27d570
### Our MongoDB url
> ~~mongodb://SEavanger:SEavanger@ds139964.mlab.com:39964/se_avangers~~
> mongodb://SEavenger:SEavenger@ds149324.mlab.com:49324/se_avengers

**Comment by hojason117** [comment]
### Backend switch to Go. Using mgo.
