### ISSUE TITLE
API can not work correctly with JWT.

### ISSUE THREAD

**Issue by YeechingTiger** [c78867886/TwitterBaby#34]
When using JWT, every api could not work.

**Comment by hojason117** [comment]
Does login work?

**Comment by YeechingTiger** [comment]
To make it clearly, only the api without JWT can work properly here. The problem is caused by CORS. When we are not using simple request, the browser will send a OPTIONS request first. The OPTIONS request is not handled correctly by the server, which cause a 400.
To solve this problem, we decided to serve our frontend code on the real server to avoid CORS.

**Comment by YeechingTiger** [comment]
There is a link which could explain this “bug”:
https://stackoverflow.com/questions/1256593/why-am-i-getting-an-options-request-instead-of-a-get-request

**Comment by hojason117** [comment]
I've pushed a fix. Plz try it out.
cause: OPTIONS request was not excluded from jwt auth.

**Comment by YeechingTiger** [comment]
Thank you Jason! Now all APIs works!
