### ISSUE TITLE
Can not use newTweet API

### ISSUE THREAD

**Issue by YeechingTiger** [c78867886/TwitterBaby#46]
When I post tweet using this api, it returns a {"message":"EOF"} message.

**Comment by c78867886** [comment]
curl -X GET http://127.0.0.1:1323/api/v1/newTweet/59cc8c95a54d75d5c8be3aa7 -H 'Content-Type: application/json' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDcxNTU1MDMsImlkIjoiNTlkMTNmMDUzMTFiYzMwM2Q4NTA4MTFjIiwidXNlcm5hbWUiOiJKYXNvbkhvIn0.uiutwoG6Hdn3EQIY4fH-KMSD95Q5HM7QVOgirxcB9dY' -d '{"message":"First tweet!"}'
This is the testing curl I use. Do you want to try it again? Thank you!

**Comment by YeechingTiger** [comment]
Using the testing curl above and getting a 404 not found response.

**Comment by c78867886** [comment]
Sorry, the user's ID has been changed. This issue can be fixed if you use the newest ID in DB.
